Pac man: Brutalist theme
shoelace-style/webawesome pull request #33
Opened 2024-02-12 18:31 UTC by frrrances

This PR adds the Brutalist theme. 

Mocks: https://www.figma.com/file/ZaBNfjLmwbX7XqJhfdoRqb/Web-Awesome-Themes?type=design&node-id=139%3A1674&mode=design&t=5DOUg5ZijG4wREir-1

2024-02-13 21:28 UTC, lindsaym-fa reviewed
This turned out so good! 👏

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/premium.css
> +  --wa-color-surface-border: var(--wa-color-base-70);
Just want to make sure this change was intentional since it really punches up some borders in dark mode.

Before:
<img width="400" alt="Screenshot 2024-02-13 at 3 51 25 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/6322c227-8f95-46ed-8199-eb3bfc4af4e0">
<img width="400" alt="Screenshot 2024-02-13 at 3 51 34 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/4cc90faf-e381-43b4-a535-a8f984a5e8fb">
<img width="400" alt="Screenshot 2024-02-13 at 3 51 43 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/29907324-7236-4b46-9b8a-0af2ecbfa89b">

After:
<img width="400" alt="Screenshot 2024-02-13 at 3 49 44 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/adc66abc-79e4-47b6-a575-a61edd77e28c">
<img width="400" alt="Screenshot 2024-02-13 at 3 49 54 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/42a31f20-efa4-4a36-81be-875384a01ef6">
<img width="400" alt="Screenshot 2024-02-13 at 3 50 02 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/4f98ed92-a3da-4c48-b4bf-7d58ca5d95f7">

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/premium.css
> +  --wa-color-neutral-text-on-surface: var(--wa-color-base-90);
Just want to verify that these changes were intentional, too.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/playful.css
> +
Do we need these rules even with this guy 👇 in `kitchen-sink.md`?
```
.support-table wa-card > * {
  border-radius: calc(var(--border-radius) - var(--border-width));
}
```

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-border-width-base: 0.0625;
```suggestion
  --wa-border-width-base: 0.125;
```

Since we have heavier borders throughout this theme, we can change this property to make sure that we thicken up everything across the board.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-form-controls-border-width: var(--wa-border-width-m);
```suggestion
  --wa-form-controls-border-width: var(--wa-border-width-s);
```

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-panel-border-width: var(--wa-border-width-m);
```suggestion
  --wa-panel-border-width: var(--wa-border-width-s);
```

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-form-controls-resting-color: var(--wa-color-neutral-border-subtle);
```suggestion
  --wa-form-controls-resting-color: var(--wa-color-neutral-border-highlight);
```

Rather than overriding the border colors for `wa-input`, `wa-select`, and `wa-checkbox`, we could use this property, which covers our inactive/deselected/unfocused color for inputs.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-form-controls-label-font-weight: var(--wa-font-weight-normal);
```suggestion
  --wa-form-controls-label-font-weight: var(--wa-font-weight-medium);
```

We have this property set up to affect label weight across all form controls instead of needing to override them individually.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    border-left: var(--wa-border-width-m) var(--wa-panel-border-style) var(--wa-color-neutral-border-subtle);
```suggestion
    border-left: var(--wa-panel-border-width) var(--wa-panel-border-style) var(--wa-color-neutral-border-subtle);
```

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    border-bottom: var(--wa-panel-border-width) var(--wa-panel-border-style) var(--wa-color-surface-border);
```suggestion
    border-bottom: var(--border-width) var(--border-style) var(--border-color);
```

Totally optional, but we could leverage the `wa-card` custom properties here to ensure this border always matches the rest of the card's borders.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    --border-width: var(--wa-panel-border-width);
```suggestion
```
Not needed if we change `--wa-border-width-base` above.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
```

Not needed if we change `--wa-form-controls-resting-color` above.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
```

Not needed if we change `--wa-border-width-base` above.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    background: var(--wa-color-base-95) url('/assets/images/kitchen-sink/brutalist/hero.png') 50% 3% no-repeat;
```suggestion
    background: var(--wa-color-surface-lowered) url('/assets/images/kitchen-sink/brutalist/hero.png') 50% 3% no-repeat;
```

This (plus an adjustment to dark mode's `--wa-color-surface-lowered` below) means that we don't have to specifically override the `background-color` for `.preview-container` in dark mode.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    border: var(--wa-border-width-m) solid var(--wa-color-brand-spot);
```suggestion
    border: var(--wa-border-width-s) solid var(--wa-color-brand-spot);
```

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
```

Not needed if we change `--wa-border-width-base` above.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +    font-weight: var(--wa-font-weight-medium);
```suggestion
```

Not needed if we change `--wa-form-controls-label-font-weight` above.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  .checkout-form wa-select::part(form-control-label) {
Do we want to generalize this to target all `wa-input` and `wa-select` labels, or is it intentionally limited to `.checkout-form`?

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-color-surface-lowered: black;
```suggestion
  --wa-color-surface-lowered: var(--wa-color-base-10);
```

This custom property is specifically meant for use cases like the `.preview-container` backdrop, so we could set this to our desired color for the container.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  --wa-color-surface-border: var(--wa-color-base-20);
```suggestion
  --wa-color-surface-border: var(--wa-color-base-10);
```

Looks like this is a shade darker in the mock-ups.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
```

If we change `--wa-color-surface-lowered` above, we won't need this rule.

2024-02-13 21:28 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
```

If we change `--wa-color-surface-border` above, we shouldn't need this rule.

2024-02-14 14:21 UTC, frrrances commented on src/themes/premium.css
> +  --wa-color-surface-border: var(--wa-color-base-70);
Hmm. Nope... Not sure how these trickled in. I'll revert them. Thanks for the catch!

2024-02-14 14:22 UTC, frrrances commented on src/themes/premium.css
> +  --wa-color-neutral-text-on-surface: var(--wa-color-base-90);
I'll revert these too.

2024-02-14 14:30 UTC, frrrances commented on src/themes/playful.css
> +
Nope! I've removed them.

2024-02-14 15:54 UTC, lindsaym-fa requested changes
Awesome! 🤩 Just one last, tiny change. 🙇

2024-02-14 15:54 UTC, lindsaym-fa commented on src/themes/brutalist.css
> +  }
```suggestion
  wa-input::part(form-control-label),
  wa-select::part(form-control-label),
  wa-radio-group::part(form-control-label) {
    font-size: var(--wa-font-size-s);
  }
```

Looks like this `wa-radio-group` fella escaped us. 👇 
<img width="554" alt="Screenshot 2024-02-14 at 10 47 09 AM" src="https://github.com/shoelace-style/webawesome/assets/126139086/fe740fc8-2cf9-4ddc-82d5-9bddbc24cc7e">

2024-02-14 16:15 UTC, frrrances commented on src/themes/brutalist.css
> +  }
it's like it's _shouting_ at us or something! thanks for catching that.

2024-02-14 16:22 UTC, lindsaym-fa approved these changes
All good!

2024-02-14 16:46 UTC, merged