Pac-Man: Polishing round 1
shoelace-style/webawesome pull request #52
Opened 2024-02-15 17:42 UTC by frrrances

Small polishing on the kitchen sink and themes.

2024-02-15 17:43 UTC, frrrances commented on src/themes/brutalist.css
> +  .token {
The default syntax highlighting colors were close but looked a bit duller, so I added these overrides. If we don't want overrides, we can probably just do without them and use the default styling. (Same for all the syntax highlighting overrides below...)

2024-02-15 23:24 UTC, lindsaym-fa requested changes
Changes look great! Just one small thing to touch up.

2024-02-15 23:24 UTC, lindsaym-fa commented on docs/pages/experimental/kitchen-sink.md
> +    border-radius: calc(var(--wa-corners-m) - var(--wa-panel-border-width));
We have some rounding sneaking into the `wa-card` images from this style.

<img width="1046" alt="Screenshot 2024-02-15 at 6 16 36 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/54e6c1c6-2903-4aef-9823-e8bfca67e12e">
<img width="1040" alt="Screenshot 2024-02-15 at 6 16 57 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/a6ff6d2c-be6f-4708-85ab-6cf498737ce3">
<img width="1035" alt="Screenshot 2024-02-15 at 6 19 32 PM" src="https://github.com/shoelace-style/webawesome/assets/126139086/a89f4688-3bdd-4c29-8960-0d2eef846307">

2024-02-16 16:18 UTC, lindsaym-fa approved these changes
All looks good to me! 🤩

2024-02-16 16:24 UTC, merged